define MAX_LEN instead of declaring as a constant
Wouldn't build on gcc 7.5.0

```
aawordsearch.c:49:21: error: initializer element is not constant
 const int MAX_LEN = GRID_SIZE - 2;
                     ^~~~~~~~~
$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```